name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-servicebolt:

    runs-on: ubuntu-latest

    steps:
 
    - name: Checkout

      uses: actions/checkout@v3

    - name: Deployment

      uses: appleboy/ssh-action@master

      with:

        host: 203.190.153.18

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        username: user
        
        port: 22

        script: |
          cd /var/www/html/servicebolt-dev/ 
          git pull origin master
      
